<?php
header('Content-Type: application/json');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    // Get JSON data from request
    $input = json_decode(file_get_contents('php://input'), true);
    
    // Extract data
    $user_name = filter_var($input['user_name'], FILTER_SANITIZE_STRING);
    $user_email = filter_var($input['user_email'], FILTER_SANITIZE_EMAIL);
    $user_phone = filter_var($input['user_phone'], FILTER_SANITIZE_STRING);
    $test_date = filter_var($input['test_date'], FILTER_SANITIZE_STRING);
    $final_wpm = filter_var($input['final_wpm'], FILTER_SANITIZE_NUMBER_INT);
    $accuracy = filter_var($input['accuracy'], FILTER_SANITIZE_STRING);
    $total_chars = filter_var($input['total_chars'], FILTER_SANITIZE_NUMBER_INT);
    $total_errors = filter_var($input['total_errors'], FILTER_SANITIZE_NUMBER_INT);
    $time_elapsed = filter_var($input['time_elapsed'], FILTER_SANITIZE_STRING);
    $lesson_name = filter_var($input['lesson_name'], FILTER_SANITIZE_STRING);
    $test_duration = filter_var($input['test_duration'], FILTER_SANITIZE_STRING);

    // Validate email
    if (!filter_var($user_email, FILTER_VALIDATE_EMAIL)) {
        echo json_encode(['success' => false, 'message' => 'Invalid email address']);
        exit;
    }

    // Email content
    $subject = "Acubens Typing Test Results - " . $test_date;
    
    $message = "
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
            .container { max-width: 600px; margin: 0 auto; background: #f9f9f9; padding: 20px; }
            .header { background: linear-gradient(135deg, #667eea, #764ba2); color: white; padding: 20px; text-align: center; }
            .results { background: white; padding: 20px; margin: 15px 0; border-radius: 8px; }
            .result-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
            .result-item { background: #f8f9fa; padding: 15px; text-align: center; border-radius: 5px; }
            .footer { text-align: center; padding: 20px; color: #666; }
        </style>
    </head>
    <body>
        <div class='container'>
            <div class='header'>
                <h1>🎯 Acubens Typing Test Report</h1>
            </div>
            
            <div class='results'>
                <p>Hello <strong>$user_name</strong>,</p>
                <p>Here are your typing test results from <strong>$test_date</strong>:</p>
                
                <div class='result-grid'>
                    <div class='result-item'>
                        <h3>$final_wpm</h3>
                        <p>Words Per Minute</p>
                    </div>
                    <div class='result-item'>
                        <h3>$accuracy</h3>
                        <p>Accuracy</p>
                    </div>
                    <div class='result-item'>
                        <h3>$total_chars</h3>
                        <p>Total Characters</p>
                    </div>
                    <div class='result-item'>
                        <h3>$total_errors</h3>
                        <p>Errors</p>
                    </div>
                </div>
                
                <div style='margin-top: 20px;'>
                    <p><strong>Time Elapsed:</strong> $time_elapsed</p>
                    <p><strong>Lesson:</strong> $lesson_name</p>
                    <p><strong>Test Duration:</strong> $test_duration</p>
                </div>
                
                <div style='background: #f0fff4; padding: 15px; border-radius: 5px; margin-top: 15px;'>
                    <h3>💡 Tips for Improvement</h3>
                    <p>• Practice daily for 15-20 minutes</p>
                    <p>• Focus on accuracy over speed initially</p>
                    <p>• Use proper finger placement</p>
                </div>
            </div>
            
            <div class='footer'>
                <p>This report was generated by Acubens Advanced Typing Test</p>
            </div>
        </div>
    </body>
    </html>
    ";

    // Email headers
    $headers = "MIME-Version: 1.0" . "\r\n";
    $headers .= "Content-type:text/html;charset=UTF-8" . "\r\n";
    $headers .= "From: Acubens Typing Test <noreply@" . $_SERVER['HTTP_HOST'] . ">" . "\r\n";
    $headers .= "Reply-To: noreply@" . $_SERVER['HTTP_HOST'] . "\r\n";
    $headers .= "X-Mailer: PHP/" . phpversion();

    // Send email
    if (mail($user_email, $subject, $message, $headers)) {
        echo json_encode(['success' => true, 'message' => 'Report sent successfully!']);
    } else {
        echo json_encode(['success' => false, 'message' => 'Failed to send email. Please try again.']);
    }
} else {
    echo json_encode(['success' => false, 'message' => 'Invalid request method']);
}
?>